### ISSUE TITLE
RPC Error: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32000,"message":"oversized data"}}' 

### ISSUE THREAD

**Issue by fedeb95** [ethjs/ethjs-query#16]
# ethjs-query

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/ethjs/ethjs-query/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/ethjs/ethjs-query/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ x] Bug (https://github.com/ethjs/ethjs-query/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/ethjs/ethjs-query/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Hi, I'm using truffle and testing a new application of mine which involves large text to be sent to a smart contract. I don't know if this is the right place to ask because maybe my issue is because of some other limit I'm not aware of, but hopefully you can point me in the right direction. I get the error above when approving a transaction with large data

## Steps to reproduce

(Add link to a demo on https://jsfiddle.net or similar if possible)

# Versions

- Node/NPM: 6.14.8
- Browser: firefox

**Comment by SilentCicero** [comment]
This error is coming from the actual Ethereum node executing the RPC request, not ethjs-query.

The truffle community would likely be able to help you more. I would join their discord. But your data is to large, maximum calldata / tx data size is around 32 KB on most nodes, but on some nodes (depending on version / kind) can go up to as high as 64-128kb.

If your using Infura, they load balance over hundreds of nodes, some won't allow more than 32kb payloads through the mempool, some will. But 32 is a safe max ATM for raw data size.

Also, 24kb is max size for Ethereum contracts atm.

Hope that helps. Good luck navigating Ethereum, may the crypto gods be with you.

**Comment by fedeb95** [comment]
thanks that's helpful! I guess I have to figure something out with multiple transactions
