### ISSUE TITLE
Bug - newFilter result and getFilterChanges params incompatible

### ISSUE THREAD

**Issue by kumavis** [ethjs/ethjs-query#9]
```js
const filterId = await eth.newFilter({ address: contractAddress, topics: [targetTopic], fromBlock: blockNumber, toBlock: 'latest' })
const filterChanges = await eth.getFilterChanges(filterId)
```

`eth.newFilter` returns a BN
`eth.getFilterChanges` converts BN to hex but does not use 'quantity' format

`<BN: 1>` becomes `0x1` instead of `0x01`

suggestion, do either or both:
- fix hex format in `getFilterChanges`
- just return hex string from `newFilter`

**Comment by kumavis** [comment]
Actually it gets worse:

as a workaround i tried
```js
const filterId = ethUtil.intToHex((await eth.newFilter(filterParams)).toNumber())
```

but `eth.getFilterChanges` still converts the correct `0x01` to `0x1`

**Comment by SilentCicero** [comment]
So I believe to fix this, I will switch newFilter / newBlockFilter and eth_newPendingTransactionFilter to return a bytes data, instead of quantity.

Then I will switch getFilterChanges to data as well, as to not convert it down to a quantity.

**Comment by SilentCicero** [comment]
However, this would break the spec, and I don't want to. I'm gonna look into a shim for getFilterChanges and logs.

**Comment by SilentCicero** [comment]
Instead, I will update for the formatting module: https://github.com/ethjs/ethjs-format/blob/master/src/index.js

**Comment by SilentCicero** [comment]
@kumavis is there a disparity between what geth / parity and TestRPC want for this value?

Is testrpc fine with 0x1 and geth is not? I'll choose whatever mainnet clients are supporting, if its 0x01, then I'll do the next push.

**Comment by kumavis** [comment]
you fixed this
